-- NOTIFICATION_ARCH TABLE --
CREATE TABLE IF NOT EXISTS DM_NOTIFICATION_ARCH (
    NOTIFICATION_ID INTEGER AUTO_INCREMENT NOT NULL,
    NOTIFICATION_CONFIG_ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID)
    );

CREATE INDEX IDX_NOTF_CONFIG_ID ON DM_NOTIFICATION_ARCH(NOTIFICATION_CONFIG_ID);
CREATE INDEX IDX_NOTF_TENANT_ID ON DM_NOTIFICATION_ARCH(TENANT_ID);
CREATE INDEX IDX_NOTF_CREATED_TIMESTAMP ON DM_NOTIFICATION_ARCH(CREATED_TIMESTAMP);
-- NOTIFICATION_ARCH TABLE END --

-- DM_NOTIFICATION_USER_ACTION_ARCH TABLE --
CREATE TABLE IF NOT EXISTS DM_NOTIFICATION_USER_ACTION_ARCH (
    ACTION_ID INTEGER AUTO_INCREMENT NOT NULL,
    NOTIFICATION_ID INTEGER NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    IS_READ BOOLEAN DEFAULT FALSE,
    ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ACTION_ID)
);

CREATE INDEX IDX_DM_NOTIFICATION_USER_ACTION_TIMESTAMP ON DM_NOTIFICATION_USER_ACTION_ARCH(ACTION_TIMESTAMP);
-- END DM_NOTIFICATION_USER_ACTION_ARCH TABLE --