
CREATE TABLE IF NOT EXISTS DM_OPERATION_ARCH (
    ID INTEGER NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_TIMESTAMP BIGINT NOT NULL,
    RECEIVED_TIMESTAMP BIGINT NULL,
    OPERATION_CODE VARCHAR(50) NOT NULL,
    INITIATED_BY VARCHAR(100) NULL,
    OPERATION_DETAILS BLOB DEFAULT NULL,
    OPERATION_PROPERTIES BLOB DEFAULT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    ARCHIVED_AT TIMESTAMP DEFAULT NOW()
)ENGINE = InnoDB;

CREATE INDEX IDX_OPR_ARC ON DM_OPERATION_ARCH(ARCHIVED_AT);

CREATE TABLE IF NOT EXISTS DM_ENROLMENT_OP_MAPPING_ARCH (
    ID INTEGER NOT NULL,
    ENROLMENT_ID INTEGER NOT NULL,
    OPERATION_ID INTEGER NOT NULL,
    STATUS VARCHAR(50) NULL,
    CREATED_TIMESTAMP INTEGER NOT NULL,
    UPDATED_TIMESTAMP INTEGER NOT NULL,
    ARCHIVED_AT TIMESTAMP DEFAULT NOW()
)ENGINE = InnoDB;

CREATE INDEX IDX_EN_OP_MAP_ARCH ON DM_ENROLMENT_OP_MAPPING_ARCH(ARCHIVED_AT);

CREATE TABLE IF NOT EXISTS DM_DEVICE_OPERATION_RESPONSE_ARCH  (
   ID  INT(11) NOT NULL,
   ENROLMENT_ID  INTEGER NOT NULL,
   OPERATION_ID  INTEGER NOT NULL,
   OPERATION_RESPONSE VARCHAR(4096) DEFAULT NULL,
   RECEIVED_TIMESTAMP  TIMESTAMP NULL,
   ARCHIVED_AT TIMESTAMP DEFAULT NOW(),
   IS_LARGE_RESPONSE BOOLEAN NOT NULL DEFAULT FALSE
)ENGINE = InnoDB;

CREATE INDEX IDX_OPR_RES_ARCH ON DM_DEVICE_OPERATION_RESPONSE_ARCH(ARCHIVED_AT);

CREATE TABLE DM_DEVICE_OPERATION_RESPONSE_LARGE_ARCH (
    ID INT(11) NOT NULL,
    OPERATION_RESPONSE LONGBLOB DEFAULT NULL,
    ARCHIVED_AT TIMESTAMP DEFAULT NOW()
)ENGINE = InnoDB;

CREATE INDEX IDX_OPR_RES_LRG_ARCH ON DM_DEVICE_OPERATION_RESPONSE_LARGE_ARCH(ARCHIVED_AT);

-- DM_NOTIFICATION_ARCH TABLES --
CREATE TABLE IF NOT EXISTS DM_NOTIFICATION_ARCH (
    NOTIFICATION_ID INTEGER AUTO_INCREMENT NOT NULL,
    NOTIFICATION_CONFIG_ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID)
    ) ENGINE = InnoDB;

CREATE INDEX IDX_NOTF_CONFIG_ID ON DM_NOTIFICATION_ARCH(NOTIFICATION_CONFIG_ID);
CREATE INDEX IDX_NOTF_TENANT_ID ON DM_NOTIFICATION_ARCH(TENANT_ID);
CREATE INDEX IDX_NOTF_CREATED_TIMESTAMP ON DM_NOTIFICATION_ARCH(CREATED_TIMESTAMP);
-- END DM_NOTIFICATION_ARCH TABLES --

-- DM_NOTIFICATION_USER_ACTION_ARCH TABLE --
CREATE TABLE IF NOT EXISTS DM_NOTIFICATION_USER_ACTION_ARCH (
    ACTION_ID INTEGER AUTO_INCREMENT NOT NULL,
    NOTIFICATION_ID INTEGER NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    IS_READ BOOLEAN DEFAULT FALSE,
    ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ACTION_ID)
);

CREATE INDEX IDX_DM_NOTIFICATION_USER_ACTION_TIMESTAMP ON DM_NOTIFICATION_USER_ACTION_ARCH(ACTION_TIMESTAMP);
-- END DM_NOTIFICATION_USER_ACTION_ARCH TABLE --
