CREATE TABLE IF NOT EXISTS DM_OPERATION_ARCH (
    ID INTEGER NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP(0) NOT NULL,
    RECEIVED_TIMESTAMP TIMESTAMP(0) NULL,
    OPERATION_CODE VARCHAR(50) NOT NULL,
    INITIATED_BY VARCHAR(100) NULL,
    OPERATION_DETAILS BYTEA DEFAULT NULL,
    OPERATION_PROPERTIES BYTEA DEFAULT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    ARCHIVED_AT TIMESTAMP(0) DEFAULT NOW()
);

CREATE INDEX IDX_OPR_ARC ON DM_OPERATION_ARCH(ARCHIVED_AT);

CREATE TABLE IF NOT EXISTS DM_ENROLMENT_OP_MAPPING_ARCH (
    ID INTEGER NOT NULL,
    ENROLMENT_ID INTEGER NOT NULL,
    OPERATION_ID INTEGER NOT NULL,
    STATUS VARCHAR(50) NULL,
    CREATED_TIMESTAMP INTEGER NOT NULL,
    UPDATED_TIMESTAMP INTEGER NOT NULL,
    ARCHIVED_AT TIMESTAMP(0) DEFAULT NOW()
);

CREATE INDEX IDX_EN_OP_MAP_ARCH ON DM_ENROLMENT_OP_MAPPING_ARCH(ARCHIVED_AT);

CREATE TABLE IF NOT EXISTS DM_DEVICE_OPERATION_RESPONSE_ARCH  (
    ID  INT NOT NULL,
    ENROLMENT_ID  INTEGER NOT NULL,
    OPERATION_ID  INTEGER NOT NULL,
    OPERATION_RESPONSE VARCHAR(4096) DEFAULT NULL,
    RECEIVED_TIMESTAMP  TIMESTAMP(0) NULL,
    ARCHIVED_AT TIMESTAMP(0) DEFAULT NOW(),
    IS_LARGE_RESPONSE BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IDX_OPR_RES_ARCH ON DM_DEVICE_OPERATION_RESPONSE_ARCH(ARCHIVED_AT);

CREATE TABLE DM_DEVICE_OPERATION_RESPONSE_LARGE_ARCH (
    ID INT NOT NULL,
    OPERATION_RESPONSE BYTEA DEFAULT NULL,
    ARCHIVED_AT TIMESTAMP(0) DEFAULT NOW()
);

CREATE INDEX IDX_OPR_RES_LRG_ARCH ON DM_DEVICE_OPERATION_RESPONSE_LARGE_ARCH(ARCHIVED_AT);

CREATE TABLE IF NOT EXISTS DM_NOTIFICATION_ARCH (
    NOTIFICATION_ID INTEGER NOT NULL,
    DEVICE_ID INTEGER NOT NULL,
    OPERATION_ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    STATUS VARCHAR(10) NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    ARCHIVED_AT TIMESTAMP(0) DEFAULT NOW()
);

CREATE INDEX IDX_NOT_ARCH ON DM_NOTIFICATION_ARCH(ARCHIVED_AT);

-- NOTIFICATION_ARCH TABLES --
CREATE SEQUENCE DM_NOTIFICATION_ARCH_seq;

CREATE TABLE IF NOT EXISTS DM_NOTIFICATION_ARCH (
                                               NOTIFICATION_ID INTEGER DEFAULT NEXTVAL('DM_NOTIFICATION_ARCH_seq') NOT NULL,
    NOTIFICATION_CONFIG_ID INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID)
    );

CREATE INDEX IDX_NOTF_CONFIG_ID ON DM_NOTIFICATION_ARCH(NOTIFICATION_CONFIG_ID);
CREATE INDEX IDX_NOTF_TENANT_ID ON DM_NOTIFICATION_ARCH(TENANT_ID);
CREATE INDEX IDX_NOTF_CREATED_TIMESTAMP ON DM_NOTIFICATION_ARCH(CREATED_TIMESTAMP);

-- END NOTIFICATION TABLES --

-- DM_NOTIFICATION_USER_ACTION TABLE --
CREATE SEQUENCE DM_NOTIFICATION_USER_ACTION_ARCH_seq;

CREATE TABLE IF NOT EXISTS DM_NOTIFICATION_USER_ACTION_ARCH (
                                                           ACTION_ID INTEGER DEFAULT NEXTVAL('DM_NOTIFICATION_USER_ACTION_ARCH_seq') NOT NULL,
    NOTIFICATION_ID INTEGER NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    IS_READ BOOLEAN DEFAULT FALSE,
    ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ACTION_ID)
);

CREATE INDEX IDX_DM_NOTIFICATION_USER_ACTION_TIMESTAMP ON DM_NOTIFICATION_USER_ACTION_ARCH(ACTION_TIMESTAMP);
-- END DM_NOTIFICATION_USER_ACTION TABLE --